version: '3'
services:
  frontend:
    build: ./streamlit-app
    env_file:
      - .env
    ports:
      - '8501:8501'
    volumes:
      - ./streamlit-app:/app
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - mynetwork
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: unless-stopped
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - mynetwork
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      -  '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    volumes:
      - db_vol_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: "dpage/pgadmin4:5.3"
    depends_on:
      - database
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_PASSWORD_FILE: ${PGADMIN_DEFAULT_PASSWORD_FILE}
      # disable spamming all the screen with logs
      GUNICORN_ACCESS_LOGFILE: /dev/null
    restart: unless-stopped
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db_vol_data:

