"""initial migration

Revision ID: 738fa211fafd
Revises: 
Create Date: 2024-07-13 13:10:17.641511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738fa211fafd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continents',
    sa.Column('continent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continent_name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('continent_id')
    )
    op.create_index(op.f('ix_continents_continent_name'), 'continents', ['continent_name'], unique=True)
    op.create_table('industries',
    sa.Column('industry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('industry_id')
    )
    op.create_index(op.f('ix_industries_industry_name'), 'industries', ['industry_name'], unique=True)
    op.create_table('jobscheduletypes',
    sa.Column('job_schedule_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_schedule_type', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('job_schedule_type_id')
    )
    op.create_index(op.f('ix_jobscheduletypes_job_schedule_type'), 'jobscheduletypes', ['job_schedule_type'], unique=True)
    op.create_table('jobsvia',
    sa.Column('job_via_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_via_name', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('job_via_id')
    )
    op.create_index(op.f('ix_jobsvia_job_via_name'), 'jobsvia', ['job_via_name'], unique=True)
    op.create_table('shortjobtitles',
    sa.Column('job_title_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_job_title_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('job_title_id')
    )
    op.create_index(op.f('ix_shortjobtitles_short_job_title_name'), 'shortjobtitles', ['short_job_title_name'], unique=True)
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=True)
    op.create_table('worklocationtypes',
    sa.Column('work_location_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_location_type', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('work_location_type_id')
    )
    op.create_index(op.f('ix_worklocationtypes_work_location_type'), 'worklocationtypes', ['work_location_type'], unique=True)
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('continent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['continent_id'], ['continents.continent_id'], ),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_index(op.f('ix_countries_country_name'), 'countries', ['country_name'], unique=True)
    op.create_table('shortjobtitleindustrieslinktable',
    sa.Column('short_job_title_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.industry_id'], ),
    sa.ForeignKeyConstraint(['short_job_title_id'], ['shortjobtitles.job_title_id'], ),
    sa.PrimaryKeyConstraint('short_job_title_id', 'industry_id')
    )
    op.create_table('cities',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_cities_city_name'), 'cities', ['city_name'], unique=True)
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('short_job_title_id', sa.Integer(), nullable=False),
    sa.Column('job_city_location_id', sa.Integer(), nullable=False),
    sa.Column('job_via_id', sa.Integer(), nullable=False),
    sa.Column('work_location_type_id', sa.Integer(), nullable=False),
    sa.Column('job_schedule_type_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['job_city_location_id'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(['job_schedule_type_id'], ['jobscheduletypes.job_schedule_type_id'], ),
    sa.ForeignKeyConstraint(['job_via_id'], ['jobsvia.job_via_id'], ),
    sa.ForeignKeyConstraint(['short_job_title_id'], ['shortjobtitles.job_title_id'], ),
    sa.ForeignKeyConstraint(['work_location_type_id'], ['worklocationtypes.work_location_type_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('jobSkillsLinkTable',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.create_table('salaries',
    sa.Column('salary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expected_yearly_salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['salary_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('salary_id')
    )
    op.create_index(op.f('ix_salaries_expected_yearly_salary'), 'salaries', ['expected_yearly_salary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salaries_expected_yearly_salary'), table_name='salaries')
    op.drop_table('salaries')
    op.drop_table('jobSkillsLinkTable')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_cities_city_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('shortjobtitleindustrieslinktable')
    op.drop_index(op.f('ix_countries_country_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_worklocationtypes_work_location_type'), table_name='worklocationtypes')
    op.drop_table('worklocationtypes')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_shortjobtitles_short_job_title_name'), table_name='shortjobtitles')
    op.drop_table('shortjobtitles')
    op.drop_index(op.f('ix_jobsvia_job_via_name'), table_name='jobsvia')
    op.drop_table('jobsvia')
    op.drop_index(op.f('ix_jobscheduletypes_job_schedule_type'), table_name='jobscheduletypes')
    op.drop_table('jobscheduletypes')
    op.drop_index(op.f('ix_industries_industry_name'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_continents_continent_name'), table_name='continents')
    op.drop_table('continents')
    # ### end Alembic commands ###
