# Define the list of countries and their respective continents
countries_and_continents = [
    {"country_name": "Afghanistan", "continent_name": "Asia"},
    {"country_name": "Argentina", "continent_name": "South America"},
    {"country_name": "Australia", "continent_name": "Australia"},
    {"country_name": "Brazil", "continent_name": "South America"},
    {"country_name": "Canada", "continent_name": "North America"},
    {"country_name": "China", "continent_name": "Asia"},
    {"country_name": "Egypt", "continent_name": "Africa"},
    {"country_name": "France", "continent_name": "Europe"},
    {"country_name": "Germany", "continent_name": "Europe"},
    {"country_name": "India", "continent_name": "Asia"},
    {"country_name": "Indonesia", "continent_name": "Asia"},
    {"country_name": "Italy", "continent_name": "Europe"},
    {"country_name": "Japan", "continent_name": "Asia"},
    {"country_name": "Kenya", "continent_name": "Africa"},
    {"country_name": "Mexico", "continent_name": "North America"},
    {"country_name": "Nigeria", "continent_name": "Africa"},
    {"country_name": "Pakistan", "continent_name": "Asia"},
    {"country_name": "Peru", "continent_name": "South America"},
    {"country_name": "Russia", "continent_name": "Europe"},
    {"country_name": "Saudi Arabia", "continent_name": "Asia"},
    {"country_name": "South Africa", "continent_name": "Africa"},
    {"country_name": "South Korea", "continent_name": "Asia"},
    {"country_name": "Spain", "continent_name": "Europe"},
    {"country_name": "Sweden", "continent_name": "Europe"},
    {"country_name": "Turkey", "continent_name": "Europe"},
    {"country_name": "United Arab Emirates", "continent_name": "Asia"},
    {"country_name": "United Kingdom", "continent_name": "Europe"},
    {"country_name": "United States", "continent_name": "North America"},
    {"country_name": "Vietnam", "continent_name": "Asia"},
    {"country_name": "Venezuela", "continent_name": "South America"},
    {"country_name": "Thailand", "continent_name": "Asia"},
    {"country_name": "Switzerland", "continent_name": "Europe"},
    {"country_name": "Portugal", "continent_name": "Europe"},
    {"country_name": "Philippines", "continent_name": "Asia"},
    {"country_name": "Norway", "continent_name": "Europe"},
    {"country_name": "Netherlands", "continent_name": "Europe"},
    {"country_name": "New Zealand", "continent_name": "Australia"},
    {"country_name": "Malaysia", "continent_name": "Asia"},
    {"country_name": "Morocco", "continent_name": "Africa"},
    {"country_name": "Nepal", "continent_name": "Asia"},
    {"country_name": "Greece", "continent_name": "Europe"},
    {"country_name": "Finland", "continent_name": "Europe"},
    {"country_name": "Chile", "continent_name": "South America"},
    {"country_name": "Bangladesh", "continent_name": "Asia"},
    {"country_name": "Colombia", "continent_name": "South America"},
    {"country_name": "Denmark", "continent_name": "Europe"},
    {"country_name": "Ethiopia", "continent_name": "Africa"},
    {"country_name": "Ghana", "continent_name": "Africa"},
    {"country_name": "Hungary", "continent_name": "Europe"},
]

continents = [
    {"continent_name": data["continent_name"]} for data in countries_and_continents
]


# List of countries and their capital cities, plus additional cities for European countries
cities_and_countries = [
    {"city_name": "Kabul", "country_name": "Afghanistan"},
    {"city_name": "Buenos Aires", "country_name": "Argentina"},
    {"city_name": "Canberra", "country_name": "Australia"},
    {"city_name": "Brasília", "country_name": "Brazil"},
    {"city_name": "Ottawa", "country_name": "Canada"},
    {"city_name": "Beijing", "country_name": "China"},
    {"city_name": "Cairo", "country_name": "Egypt"},
    {"city_name": "Paris", "country_name": "France"},
    {"city_name": "Marseille", "country_name": "France"},
    {"city_name": "Berlin", "country_name": "Germany"},
    {"city_name": "Munich", "country_name": "Germany"},
    {"city_name": "Frankfurt", "country_name": "Germany"},
    {"city_name": "New Delhi", "country_name": "India"},
    {"city_name": "Jakarta", "country_name": "Indonesia"},
    {"city_name": "Rome", "country_name": "Italy"},
    {"city_name": "Milan", "country_name": "Italy"},
    {"city_name": "Naples", "country_name": "Italy"},
    {"city_name": "Tokyo", "country_name": "Japan"},
    {"city_name": "Nairobi", "country_name": "Kenya"},
    {"city_name": "Mexico City", "country_name": "Mexico"},
    {"city_name": "Abuja", "country_name": "Nigeria"},
    {"city_name": "Islamabad", "country_name": "Pakistan"},
    {"city_name": "Lima", "country_name": "Peru"},
    {"city_name": "Moscow", "country_name": "Russia"},
    {"city_name": "Saint Petersburg", "country_name": "Russia"},
    {"city_name": "Riyadh", "country_name": "Saudi Arabia"},
    {"city_name": "Pretoria", "country_name": "South Africa"},
    {"city_name": "Johannesburg", "country_name": "South Africa"},
    {"city_name": "Seoul", "country_name": "South Korea"},
    {"city_name": "Madrid", "country_name": "Spain"},
    {"city_name": "Barcelona", "country_name": "Spain"},
    {"city_name": "Valencia", "country_name": "Spain"},
    {"city_name": "Stockholm", "country_name": "Sweden"},
    {"city_name": "Gothenburg", "country_name": "Sweden"},
    {"city_name": "Malmö", "country_name": "Sweden"},
    {"city_name": "Ankara", "country_name": "Turkey"},
    {"city_name": "Istanbul", "country_name": "Turkey"},
    {"city_name": "Izmir", "country_name": "Turkey"},
    {"city_name": "Abu Dhabi", "country_name": "United Arab Emirates"},
    {"city_name": "London", "country_name": "United Kingdom"},
    {"city_name": "Birmingham", "country_name": "United Kingdom"},
    {"city_name": "Manchester", "country_name": "United Kingdom"},
    {"city_name": "Washington, D.C.", "country_name": "United States"},
    {"city_name": "New York", "country_name": "United States"},
    {"city_name": "Los Angeles", "country_name": "United States"},
    {"city_name": "Hanoi", "country_name": "Vietnam"},
    {"city_name": "Ho Chi Minh City", "country_name": "Vietnam"},
    {"city_name": "Caracas", "country_name": "Venezuela"},
    {"city_name": "Bangkok", "country_name": "Thailand"},
    {"city_name": "Bern", "country_name": "Switzerland"},
    {"city_name": "Zurich", "country_name": "Switzerland"},
    {"city_name": "Geneva", "country_name": "Switzerland"},
    {"city_name": "Lisbon", "country_name": "Portugal"},
    {"city_name": "Porto", "country_name": "Portugal"},
    {"city_name": "Manila", "country_name": "Philippines"},
    {"city_name": "Oslo", "country_name": "Norway"},
    {"city_name": "Bergen", "country_name": "Norway"},
    {"city_name": "Amsterdam", "country_name": "Netherlands"},
    {"city_name": "Rotterdam", "country_name": "Netherlands"},
    {"city_name": "The Hague", "country_name": "Netherlands"},
    {"city_name": "Wellington", "country_name": "New Zealand"},
    {"city_name": "Auckland", "country_name": "New Zealand"},
    {"city_name": "Kuala Lumpur", "country_name": "Malaysia"},
    {"city_name": "Rabat", "country_name": "Morocco"},
    {"city_name": "Casablanca", "country_name": "Morocco"},
    {"city_name": "Kathmandu", "country_name": "Nepal"},
    {"city_name": "Athens", "country_name": "Greece"},
    {"city_name": "Thessaloniki", "country_name": "Greece"},
    {"city_name": "Helsinki", "country_name": "Finland"},
    {"city_name": "Turku", "country_name": "Finland"},
    {"city_name": "Santiago", "country_name": "Chile"},
    {"city_name": "Valparaíso", "country_name": "Chile"},
    {"city_name": "Dhaka", "country_name": "Bangladesh"},
    {"city_name": "Chittagong", "country_name": "Bangladesh"},
    {"city_name": "Bogotá", "country_name": "Colombia"},
    {"city_name": "Medellín", "country_name": "Colombia"},
    {"city_name": "Copenhagen", "country_name": "Denmark"},
    {"city_name": "Aarhus", "country_name": "Denmark"},
    {"city_name": "Addis Ababa", "country_name": "Ethiopia"},
    {"city_name": "Accra", "country_name": "Ghana"},
    {"city_name": "Budapest", "country_name": "Hungary"},
    {"city_name": "Debrecen", "country_name": "Hungary"},
]

# List of industries
industries = [
    {"industry_name": "Agriculture"},
    {"industry_name": "Automotive"},
    {"industry_name": "Aerospace"},
    {"industry_name": "Banking"},
    {"industry_name": "Biotechnology"},
    {"industry_name": "Construction"},
    {"industry_name": "Consumer Goods"},
    {"industry_name": "Defense"},
    {"industry_name": "Education"},
    {"industry_name": "Energy"},
    {"industry_name": "Entertainment"},
    {"industry_name": "Fashion"},
    {"industry_name": "Financial Services"},
    {"industry_name": "Food & Beverage"},
    {"industry_name": "Healthcare"},
    {"industry_name": "Hospitality"},
    {"industry_name": "Information Technology"},
    {"industry_name": "Insurance"},
    {"industry_name": "Legal Services"},
    {"industry_name": "Logistics"},
    {"industry_name": "Manufacturing"},
    {"industry_name": "Media"},
    {"industry_name": "Mining"},
    {"industry_name": "Non-Profit"},
    {"industry_name": "Oil & Gas"},
    {"industry_name": "Pharmaceuticals"},
    {"industry_name": "Professional Services"},
    {"industry_name": "Public Sector"},
    {"industry_name": "Real Estate"},
    {"industry_name": "Retail"},
    {"industry_name": "Telecommunications"},
    {"industry_name": "Transportation"},
    {"industry_name": "Utilities"},
    {"industry_name": "Venture Capital"},
    {"industry_name": "Wholesale"},
    {"industry_name": "Renewable Energy"},
    {"industry_name": "Advertising"},
    {"industry_name": "Consulting"},
    {"industry_name": "E-commerce"},
    {"industry_name": "Event Management"},
    {"industry_name": "Gaming"},
    {"industry_name": "Human Resources"},
    {"industry_name": "Interior Design"},
    {"industry_name": "Market Research"},
    {"industry_name": "Publishing"},
    {"industry_name": "Sports"},
    {"industry_name": "Tourism"},
    {"industry_name": "Waste Management"},
    {"industry_name": "Architecture"},
    {"industry_name": "Cybersecurity"},
    {"industry_name": "Fintech"},
]

# List of short job titles and corresponding industries
job_titles_and_industries = [
    {"short_job_title": "Analyst", "industry_name": "Agriculture"},
    {"short_job_title": "Agronomist", "industry_name": "Agriculture"},
    {"short_job_title": "Engineer", "industry_name": "Automotive"},
    {"short_job_title": "Mechanic", "industry_name": "Automotive"},
    {"short_job_title": "Technician", "industry_name": "Aerospace"},
    {"short_job_title": "Pilot", "industry_name": "Aerospace"},
    {"short_job_title": "Manager", "industry_name": "Banking"},
    {"short_job_title": "Teller", "industry_name": "Banking"},
    {"short_job_title": "Researcher", "industry_name": "Biotechnology"},
    {"short_job_title": "Lab Technician", "industry_name": "Biotechnology"},
    {"short_job_title": "Supervisor", "industry_name": "Construction"},
    {"short_job_title": "Architect", "industry_name": "Construction"},
    {"short_job_title": "Designer", "industry_name": "Consumer Goods"},
    {"short_job_title": "Product Manager", "industry_name": "Consumer Goods"},
    {"short_job_title": "Specialist", "industry_name": "Defense"},
    {"short_job_title": "Soldier", "industry_name": "Defense"},
    {"short_job_title": "Teacher", "industry_name": "Education"},
    {"short_job_title": "Professor", "industry_name": "Education"},
    {"short_job_title": "Consultant", "industry_name": "Energy"},
    {"short_job_title": "Engineer", "industry_name": "Energy"},
    {"short_job_title": "Producer", "industry_name": "Entertainment"},
    {"short_job_title": "Director", "industry_name": "Entertainment"},
    {"short_job_title": "Stylist", "industry_name": "Fashion"},
    {"short_job_title": "Designer", "industry_name": "Fashion"},
    {"short_job_title": "Advisor", "industry_name": "Financial Services"},
    {"short_job_title": "Analyst", "industry_name": "Financial Services"},
    {"short_job_title": "Chef", "industry_name": "Food & Beverage"},
    {"short_job_title": "Bartender", "industry_name": "Food & Beverage"},
    {"short_job_title": "Nurse", "industry_name": "Healthcare"},
    {"short_job_title": "Doctor", "industry_name": "Healthcare"},
    {"short_job_title": "Receptionist", "industry_name": "Hospitality"},
    {"short_job_title": "Manager", "industry_name": "Hospitality"},
    {"short_job_title": "Developer", "industry_name": "Information Technology"},
    {
        "short_job_title": "System Administrator",
        "industry_name": "Information Technology",
    },
    {"short_job_title": "Underwriter", "industry_name": "Insurance"},
    {"short_job_title": "Agent", "industry_name": "Insurance"},
    {"short_job_title": "Paralegal", "industry_name": "Legal Services"},
    {"short_job_title": "Attorney", "industry_name": "Legal Services"},
    {"short_job_title": "Coordinator", "industry_name": "Logistics"},
    {"short_job_title": "Dispatcher", "industry_name": "Logistics"},
    {"short_job_title": "Operator", "industry_name": "Manufacturing"},
    {"short_job_title": "Quality Inspector", "industry_name": "Manufacturing"},
    {"short_job_title": "Journalist", "industry_name": "Media"},
    {"short_job_title": "Editor", "industry_name": "Media"},
    {"short_job_title": "Geologist", "industry_name": "Mining"},
    {"short_job_title": "Miner", "industry_name": "Mining"},
    {"short_job_title": "Director", "industry_name": "Non-Profit"},
    {"short_job_title": "Coordinator", "industry_name": "Non-Profit"},
    {"short_job_title": "Geologist", "industry_name": "Oil & Gas"},
    {"short_job_title": "Engineer", "industry_name": "Oil & Gas"},
    {"short_job_title": "Pharmacist", "industry_name": "Pharmaceuticals"},
    {"short_job_title": "Researcher", "industry_name": "Pharmaceuticals"},
    {"short_job_title": "Consultant", "industry_name": "Professional Services"},
    {"short_job_title": "Advisor", "industry_name": "Professional Services"},
    {"short_job_title": "Administrator", "industry_name": "Public Sector"},
    {"short_job_title": "Civil Servant", "industry_name": "Public Sector"},
    {"short_job_title": "Agent", "industry_name": "Real Estate"},
    {"short_job_title": "Broker", "industry_name": "Real Estate"},
    {"short_job_title": "Cashier", "industry_name": "Retail"},
    {"short_job_title": "Store Manager", "industry_name": "Retail"},
    {"short_job_title": "Technician", "industry_name": "Telecommunications"},
    {"short_job_title": "Network Engineer", "industry_name": "Telecommunications"},
    {"short_job_title": "Driver", "industry_name": "Transportation"},
    {"short_job_title": "Pilot", "industry_name": "Transportation"},
    {"short_job_title": "Technician", "industry_name": "Utilities"},
    {"short_job_title": "Engineer", "industry_name": "Utilities"},
    {"short_job_title": "Analyst", "industry_name": "Venture Capital"},
    {"short_job_title": "Investor", "industry_name": "Venture Capital"},
    {"short_job_title": "Salesperson", "industry_name": "Wholesale"},
    {"short_job_title": "Manager", "industry_name": "Wholesale"},
    {"short_job_title": "Engineer", "industry_name": "Renewable Energy"},
    {"short_job_title": "Technician", "industry_name": "Renewable Energy"},
    {"short_job_title": "Marketer", "industry_name": "Advertising"},
    {"short_job_title": "Copywriter", "industry_name": "Advertising"},
    {"short_job_title": "Analyst", "industry_name": "Consulting"},
    {"short_job_title": "Advisor", "industry_name": "Consulting"},
    {"short_job_title": "Developer", "industry_name": "E-commerce"},
    {"short_job_title": "Product Manager", "industry_name": "E-commerce"},
    {"short_job_title": "Coordinator", "industry_name": "Event Management"},
    {"short_job_title": "Planner", "industry_name": "Event Management"},
    {"short_job_title": "Developer", "industry_name": "Gaming"},
    {"short_job_title": "Designer", "industry_name": "Gaming"},
    {"short_job_title": "Recruiter", "industry_name": "Human Resources"},
    {"short_job_title": "Trainer", "industry_name": "Human Resources"},
    {"short_job_title": "Designer", "industry_name": "Interior Design"},
    {"short_job_title": "Decorator", "industry_name": "Interior Design"},
    {"short_job_title": "Analyst", "industry_name": "Market Research"},
    {"short_job_title": "Surveyor", "industry_name": "Market Research"},
    {"short_job_title": "Editor", "industry_name": "Publishing"},
    {"short_job_title": "Writer", "industry_name": "Publishing"},
    {"short_job_title": "Coach", "industry_name": "Sports"},
    {"short_job_title": "Trainer", "industry_name": "Sports"},
    {"short_job_title": "Guide", "industry_name": "Tourism"},
    {"short_job_title": "Agent", "industry_name": "Tourism"},
    {"short_job_title": "Technician", "industry_name": "Waste Management"},
    {"short_job_title": "Supervisor", "industry_name": "Waste Management"},
    {"short_job_title": "Architect", "industry_name": "Architecture"},
    {"short_job_title": "Designer", "industry_name": "Architecture"},
    {"short_job_title": "Analyst", "industry_name": "Cybersecurity"},
    {"short_job_title": "Technician", "industry_name": "Cybersecurity"},
    {"short_job_title": "Developer", "industry_name": "Fintech"},
    {"short_job_title": "Analyst", "industry_name": "Fintech"},
]


work_location_types_data = [
    {"work_location_type": "On-site"},
    {"work_location_type": "Remote"},
    {"work_location_type": "Hybrid"},
]

job_schedule_types_data = [
    {"job_schedule_type": "Full-time"},
    {"job_schedule_type": "Part-time"},
    {"job_schedule_type": "Contract"},
]

# List of job via names
job_via_names = [
    {"job_via_name": "LinkedIn"},
    {"job_via_name": "Indeed"},
    {"job_via_name": "Glassdoor"},
    {"job_via_name": "Monster"},
    {"job_via_name": "ZipRecruiter"},
    {"job_via_name": "CareerBuilder"},
    {"job_via_name": "SimplyHired"},
    {"job_via_name": "FlexJobs"},
    {"job_via_name": "AngelList"},
    {"job_via_name": "Dice"},
    {"job_via_name": "Upwork"},
    {"job_via_name": "Freelancer"},
    {"job_via_name": "Craigslist"},
    {"job_via_name": "Snagajob"},
    {"job_via_name": "Jobvite"},
]

# List of companies corresponding to the countries
companies = [
    {"company_name": "Afghan Wireless", "country_name": "Afghanistan"},
    {"company_name": "YPF", "country_name": "Argentina"},
    {"company_name": "BHP", "country_name": "Australia"},
    {"company_name": "Petrobras", "country_name": "Brazil"},
    {"company_name": "Shopify", "country_name": "Canada"},
    {"company_name": "Huawei", "country_name": "China"},
    {"company_name": "Orascom Construction", "country_name": "Egypt"},
    {"company_name": "Airbus", "country_name": "France"},
    {"company_name": "L'Oréal", "country_name": "France"},
    {"company_name": "Danone", "country_name": "France"},
    {"company_name": "Volkswagen", "country_name": "Germany"},
    {"company_name": "Siemens", "country_name": "Germany"},
    {"company_name": "BMW", "country_name": "Germany"},
    {"company_name": "Tata Group", "country_name": "India"},
    {"company_name": "Unilever Indonesia", "country_name": "Indonesia"},
    {"company_name": "Ferrari", "country_name": "Italy"},
    {"company_name": "Enel", "country_name": "Italy"},
    {"company_name": "Fiat", "country_name": "Italy"},
    {"company_name": "Toyota", "country_name": "Japan"},
    {"company_name": "Sony", "country_name": "Japan"},
    {"company_name": "Honda", "country_name": "Japan"},
    {"company_name": "Safaricom", "country_name": "Kenya"},
    {"company_name": "Cemex", "country_name": "Mexico"},
    {"company_name": "Bimbo", "country_name": "Mexico"},
    {"company_name": "Pemex", "country_name": "Mexico"},
    {"company_name": "Dangote Group", "country_name": "Nigeria"},
    {"company_name": "Pak Elektron", "country_name": "Pakistan"},
    {"company_name": "Engro Corporation", "country_name": "Pakistan"},
    {"company_name": "Petroperú", "country_name": "Peru"},
    {"company_name": "Gazprom", "country_name": "Russia"},
    {"company_name": "Lukoil", "country_name": "Russia"},
    {"company_name": "Saudi Aramco", "country_name": "Saudi Arabia"},
    {"company_name": "Sasol", "country_name": "South Africa"},
    {"company_name": "Samsung", "country_name": "South Korea"},
    {"company_name": "Hyundai", "country_name": "South Korea"},
    {"company_name": "Inditex", "country_name": "Spain"},
    {"company_name": "Banco Santander", "country_name": "Spain"},
    {"company_name": "Volvo", "country_name": "Sweden"},
    {"company_name": "Ericsson", "country_name": "Sweden"},
    {"company_name": "Koç Holding", "country_name": "Turkey"},
    {"company_name": "Turkish Airlines", "country_name": "Turkey"},
    {"company_name": "Emirates", "country_name": "United Arab Emirates"},
    {"company_name": "Etihad Airways", "country_name": "United Arab Emirates"},
    {"company_name": "BP", "country_name": "United Kingdom"},
    {"company_name": "HSBC", "country_name": "United Kingdom"},
    {"company_name": "Vodafone", "country_name": "United Kingdom"},
    {"company_name": "Apple Inc.", "country_name": "United States"},
    {"company_name": "Microsoft", "country_name": "United States"},
    {"company_name": "Amazon", "country_name": "United States"},
    {"company_name": "Vingroup", "country_name": "Vietnam"},
    {"company_name": "Viettel", "country_name": "Vietnam"},
    {"company_name": "PDVSA", "country_name": "Venezuela"},
    {"company_name": "PTT", "country_name": "Thailand"},
    {"company_name": "Thai Airways", "country_name": "Thailand"},
    {"company_name": "Nestle", "country_name": "Switzerland"},
    {"company_name": "Roche", "country_name": "Switzerland"},
    {"company_name": "EDP", "country_name": "Portugal"},
    {"company_name": "Galp Energia", "country_name": "Portugal"},
    {"company_name": "SM Investments", "country_name": "Philippines"},
    {"company_name": "San Miguel Corporation", "country_name": "Philippines"},
    {"company_name": "Equinor", "country_name": "Norway"},
    {"company_name": "Telenor", "country_name": "Norway"},
    {"company_name": "Shell", "country_name": "Netherlands"},
    {"company_name": "Heineken", "country_name": "Netherlands"},
    {"company_name": "Fonterra", "country_name": "New Zealand"},
    {"company_name": "Air New Zealand", "country_name": "New Zealand"},
    {"company_name": "Petronas", "country_name": "Malaysia"},
    {"company_name": "Maybank", "country_name": "Malaysia"},
    {"company_name": "OCP Group", "country_name": "Morocco"},
    {"company_name": "BMCE Bank", "country_name": "Morocco"},
    {"company_name": "Ncell", "country_name": "Nepal"},
    {"company_name": "Nabil Bank", "country_name": "Nepal"},
    {"company_name": "Hellenic Petroleum", "country_name": "Greece"},
    {"company_name": "Alpha Bank", "country_name": "Greece"},
    {"company_name": "Nokia", "country_name": "Finland"},
    {"company_name": "Kone", "country_name": "Finland"},
    {"company_name": "Codelco", "country_name": "Chile"},
    {"company_name": "LAN Airlines", "country_name": "Chile"},
    {"company_name": "Grameenphone", "country_name": "Bangladesh"},
    {"company_name": "BRAC Bank", "country_name": "Bangladesh"},
    {"company_name": "Ecopetrol", "country_name": "Colombia"},
    {"company_name": "Bancolombia", "country_name": "Colombia"},
    {"company_name": "Novo Nordisk", "country_name": "Denmark"},
    {"company_name": "Maersk", "country_name": "Denmark"},
    {"company_name": "Ethio Telecom", "country_name": "Ethiopia"},
    {"company_name": "Ethiopian Airlines", "country_name": "Ethiopia"},
    {"company_name": "GCB Bank", "country_name": "Ghana"},
    {"company_name": "MTN Ghana", "country_name": "Ghana"},
    {"company_name": "MOL Group", "country_name": "Hungary"},
    {"company_name": "OTP Bank", "country_name": "Hungary"},
]


# List of detailed job titles corresponding to each short job title
detailed_job_titles = [
    {"job_title": "Financial Analyst", "short_job_title": "Analyst"},
    {"job_title": "Market Research Analyst", "short_job_title": "Analyst"},
    {"job_title": "Data Analyst", "short_job_title": "Analyst"},
    {"job_title": "Business Analyst", "short_job_title": "Analyst"},
    {"job_title": "Operations Analyst", "short_job_title": "Analyst"},
    {"job_title": "Investment Analyst", "short_job_title": "Analyst"},
    {"job_title": "Software Engineer", "short_job_title": "Engineer"},
    {"job_title": "Mechanical Engineer", "short_job_title": "Engineer"},
    {"job_title": "Electrical Engineer", "short_job_title": "Engineer"},
    {"job_title": "Civil Engineer", "short_job_title": "Engineer"},
    {"job_title": "Chemical Engineer", "short_job_title": "Engineer"},
    {"job_title": "Environmental Engineer", "short_job_title": "Engineer"},
    {"job_title": "Lab Technician", "short_job_title": "Technician"},
    {"job_title": "IT Technician", "short_job_title": "Technician"},
    {"job_title": "Maintenance Technician", "short_job_title": "Technician"},
    {"job_title": "Electrical Technician", "short_job_title": "Technician"},
    {"job_title": "Mechanical Technician", "short_job_title": "Technician"},
    {"job_title": "Network Technician", "short_job_title": "Technician"},
    {"job_title": "Project Manager", "short_job_title": "Manager"},
    {"job_title": "Operations Manager", "short_job_title": "Manager"},
    {"job_title": "Product Manager", "short_job_title": "Manager"},
    {"job_title": "Sales Manager", "short_job_title": "Manager"},
    {"job_title": "Marketing Manager", "short_job_title": "Manager"},
    {"job_title": "Human Resources Manager", "short_job_title": "Manager"},
    {"job_title": "Medical Researcher", "short_job_title": "Researcher"},
    {"job_title": "Scientific Researcher", "short_job_title": "Researcher"},
    {"job_title": "Market Researcher", "short_job_title": "Researcher"},
    {"job_title": "Field Researcher", "short_job_title": "Researcher"},
    {"job_title": "Policy Researcher", "short_job_title": "Researcher"},
    {"job_title": "Social Science Researcher", "short_job_title": "Researcher"},
    {"job_title": "Construction Supervisor", "short_job_title": "Supervisor"},
    {"job_title": "Manufacturing Supervisor", "short_job_title": "Supervisor"},
    {"job_title": "Maintenance Supervisor", "short_job_title": "Supervisor"},
    {"job_title": "Logistics Supervisor", "short_job_title": "Supervisor"},
    {"job_title": "Production Supervisor", "short_job_title": "Supervisor"},
    {"job_title": "Retail Supervisor", "short_job_title": "Supervisor"},
    {"job_title": "Graphic Designer", "short_job_title": "Designer"},
    {"job_title": "Interior Designer", "short_job_title": "Designer"},
    {"job_title": "Product Designer", "short_job_title": "Designer"},
    {"job_title": "Web Designer", "short_job_title": "Designer"},
    {"job_title": "Fashion Designer", "short_job_title": "Designer"},
    {"job_title": "UX/UI Designer", "short_job_title": "Designer"},
    {"job_title": "Customer Support Specialist", "short_job_title": "Specialist"},
    {"job_title": "IT Support Specialist", "short_job_title": "Specialist"},
    {"job_title": "Marketing Specialist", "short_job_title": "Specialist"},
    {"job_title": "HR Specialist", "short_job_title": "Specialist"},
    {"job_title": "Financial Specialist", "short_job_title": "Specialist"},
    {"job_title": "Sales Specialist", "short_job_title": "Specialist"},
    {"job_title": "Elementary School Teacher", "short_job_title": "Teacher"},
    {"job_title": "High School Teacher", "short_job_title": "Teacher"},
    {"job_title": "Special Education Teacher", "short_job_title": "Teacher"},
    {"job_title": "ESL Teacher", "short_job_title": "Teacher"},
    {"job_title": "Substitute Teacher", "short_job_title": "Teacher"},
    {"job_title": "Kindergarten Teacher", "short_job_title": "Teacher"},
    {"job_title": "Business Consultant", "short_job_title": "Consultant"},
    {"job_title": "Financial Consultant", "short_job_title": "Consultant"},
    {"job_title": "IT Consultant", "short_job_title": "Consultant"},
    {"job_title": "Management Consultant", "short_job_title": "Consultant"},
    {"job_title": "HR Consultant", "short_job_title": "Consultant"},
    {"job_title": "Strategy Consultant", "short_job_title": "Consultant"},
    {"job_title": "Film Producer", "short_job_title": "Producer"},
    {"job_title": "Music Producer", "short_job_title": "Producer"},
    {"job_title": "Television Producer", "short_job_title": "Producer"},
    {"job_title": "Theater Producer", "short_job_title": "Producer"},
    {"job_title": "Video Producer", "short_job_title": "Producer"},
    {"job_title": "Event Producer", "short_job_title": "Producer"},
    {"job_title": "Hair Stylist", "short_job_title": "Stylist"},
    {"job_title": "Fashion Stylist", "short_job_title": "Stylist"},
    {"job_title": "Wardrobe Stylist", "short_job_title": "Stylist"},
    {"job_title": "Makeup Stylist", "short_job_title": "Stylist"},
    {"job_title": "Interior Stylist", "short_job_title": "Stylist"},
    {"job_title": "Personal Stylist", "short_job_title": "Stylist"},
    {"job_title": "Financial Advisor", "short_job_title": "Advisor"},
    {"job_title": "Career Advisor", "short_job_title": "Advisor"},
    {"job_title": "Academic Advisor", "short_job_title": "Advisor"},
    {"job_title": "Legal Advisor", "short_job_title": "Advisor"},
    {"job_title": "Customer Service Advisor", "short_job_title": "Advisor"},
    {"job_title": "Investment Advisor", "short_job_title": "Advisor"},
    {"job_title": "Executive Chef", "short_job_title": "Chef"},
    {"job_title": "Sous Chef", "short_job_title": "Chef"},
    {"job_title": "Pastry Chef", "short_job_title": "Chef"},
    {"job_title": "Line Chef", "short_job_title": "Chef"},
    {"job_title": "Personal Chef", "short_job_title": "Chef"},
    {"job_title": "Banquet Chef", "short_job_title": "Chef"},
    {"job_title": "Registered Nurse", "short_job_title": "Nurse"},
    {"job_title": "Nurse Practitioner", "short_job_title": "Nurse"},
    {"job_title": "Clinical Nurse", "short_job_title": "Nurse"},
    {"job_title": "Pediatric Nurse", "short_job_title": "Nurse"},
    {"job_title": "ER Nurse", "short_job_title": "Nurse"},
    {"job_title": "Surgical Nurse", "short_job_title": "Nurse"},
    {"job_title": "Front Desk Receptionist", "short_job_title": "Receptionist"},
    {"job_title": "Medical Receptionist", "short_job_title": "Receptionist"},
    {"job_title": "Dental Receptionist", "short_job_title": "Receptionist"},
    {"job_title": "Hotel Receptionist", "short_job_title": "Receptionist"},
    {"job_title": "Corporate Receptionist", "short_job_title": "Receptionist"},
    {"job_title": "Salon Receptionist", "short_job_title": "Receptionist"},
    {"job_title": "Software Developer", "short_job_title": "Developer"},
    {"job_title": "Web Developer", "short_job_title": "Developer"},
    {"job_title": "Mobile App Developer", "short_job_title": "Developer"},
    {"job_title": "Game Developer", "short_job_title": "Developer"},
    {"job_title": "Frontend Developer", "short_job_title": "Developer"},
    {"job_title": "Backend Developer", "short_job_title": "Developer"},
    {"job_title": "Insurance Underwriter", "short_job_title": "Underwriter"},
    {"job_title": "Loan Underwriter", "short_job_title": "Underwriter"},
    {"job_title": "Mortgage Underwriter", "short_job_title": "Underwriter"},
    {"job_title": "Health Insurance Underwriter", "short_job_title": "Underwriter"},
    {"job_title": "Life Insurance Underwriter", "short_job_title": "Underwriter"},
    {
        "job_title": "Property and Casualty Underwriter",
        "short_job_title": "Underwriter",
    },
    {"job_title": "Corporate Paralegal", "short_job_title": "Paralegal"},
    {"job_title": "Litigation Paralegal", "short_job_title": "Paralegal"},
    {"job_title": "Immigration Paralegal", "short_job_title": "Paralegal"},
    {"job_title": "Real Estate Paralegal", "short_job_title": "Paralegal"},
    {"job_title": "Family Law Paralegal", "short_job_title": "Paralegal"},
    {"job_title": "IP Paralegal", "short_job_title": "Paralegal"},
    {"job_title": "Logistics Coordinator", "short_job_title": "Coordinator"},
    {"job_title": "Project Coordinator", "short_job_title": "Coordinator"},
    {"job_title": "Event Coordinator", "short_job_title": "Coordinator"},
    {"job_title": "Marketing Coordinator", "short_job_title": "Coordinator"},
    {"job_title": "Sales Coordinator", "short_job_title": "Coordinator"},
    {"job_title": "HR Coordinator", "short_job_title": "Coordinator"},
    {"job_title": "Machine Operator", "short_job_title": "Operator"},
    {"job_title": "Heavy Equipment Operator", "short_job_title": "Operator"},
    {"job_title": "Crane Operator", "short_job_title": "Operator"},
    {"job_title": "Forklift Operator", "short_job_title": "Operator"},
    {"job_title": "Plant Operator", "short_job_title": "Operator"},
    {"job_title": "Production Operator", "short_job_title": "Operator"},
    {"job_title": "News Journalist", "short_job_title": "Journalist"},
    {"job_title": "Broadcast Journalist", "short_job_title": "Journalist"},
    {"job_title": "Sports Journalist", "short_job_title": "Journalist"},
    {"job_title": "Investigative Journalist", "short_job_title": "Journalist"},
    {"job_title": "Freelance Journalist", "short_job_title": "Journalist"},
    {"job_title": "Photojournalist", "short_job_title": "Journalist"},
    {"job_title": "Field Geologist", "short_job_title": "Geologist"},
    {"job_title": "Environmental Geologist", "short_job_title": "Geologist"},
    {"job_title": "Petroleum Geologist", "short_job_title": "Geologist"},
    {"job_title": "Mining Geologist", "short_job_title": "Geologist"},
    {"job_title": "Engineering Geologist", "short_job_title": "Geologist"},
    {"job_title": "Hydrogeologist", "short_job_title": "Geologist"},
    {"job_title": "Executive Director", "short_job_title": "Director"},
    {"job_title": "Program Director", "short_job_title": "Director"},
    {"job_title": "Creative Director", "short_job_title": "Director"},
    {"job_title": "Marketing Director", "short_job_title": "Director"},
    {"job_title": "Technical Director", "short_job_title": "Director"},
    {"job_title": "Art Director", "short_job_title": "Director"},
    {"job_title": "Oil and Gas Geologist", "short_job_title": "Geologist"},
    {"job_title": "Reservoir Geologist", "short_job_title": "Geologist"},
    {"job_title": "Production Geologist", "short_job_title": "Geologist"},
    {"job_title": "Exploration Geologist", "short_job_title": "Geologist"},
    {"job_title": "Petrophysicist", "short_job_title": "Geologist"},
    {"job_title": "Mud Logger", "short_job_title": "Geologist"},
    {"job_title": "Clinical Pharmacist", "short_job_title": "Pharmacist"},
    {"job_title": "Retail Pharmacist", "short_job_title": "Pharmacist"},
    {"job_title": "Hospital Pharmacist", "short_job_title": "Pharmacist"},
    {"job_title": "Research Pharmacist", "short_job_title": "Pharmacist"},
    {"job_title": "Nuclear Pharmacist", "short_job_title": "Pharmacist"},
    {"job_title": "Industrial Pharmacist", "short_job_title": "Pharmacist"},
    {"job_title": "Business Consultant", "short_job_title": "Consultant"},
    {"job_title": "Management Consultant", "short_job_title": "Consultant"},
    {"job_title": "Strategy Consultant", "short_job_title": "Consultant"},
    {"job_title": "Technology Consultant", "short_job_title": "Consultant"},
    {"job_title": "HR Consultant", "short_job_title": "Consultant"},
    {"job_title": "Financial Consultant", "short_job_title": "Consultant"},
    {"job_title": "Administrative Assistant", "short_job_title": "Administrator"},
    {"job_title": "Office Administrator", "short_job_title": "Administrator"},
    {"job_title": "Systems Administrator", "short_job_title": "Administrator"},
    {"job_title": "Database Administrator", "short_job_title": "Administrator"},
    {"job_title": "Network Administrator", "short_job_title": "Administrator"},
    {"job_title": "School Administrator", "short_job_title": "Administrator"},
    {"job_title": "Real Estate Agent", "short_job_title": "Agent"},
    {"job_title": "Travel Agent", "short_job_title": "Agent"},
    {"job_title": "Insurance Agent", "short_job_title": "Agent"},
    {"job_title": "Sports Agent", "short_job_title": "Agent"},
    {"job_title": "Talent Agent", "short_job_title": "Agent"},
    {"job_title": "Customs Agent", "short_job_title": "Agent"},
    {"job_title": "Retail Cashier", "short_job_title": "Cashier"},
    {"job_title": "Bank Cashier", "short_job_title": "Cashier"},
    {"job_title": "Grocery Store Cashier", "short_job_title": "Cashier"},
    {"job_title": "Restaurant Cashier", "short_job_title": "Cashier"},
    {"job_title": "Movie Theater Cashier", "short_job_title": "Cashier"},
    {"job_title": "Parking Lot Cashier", "short_job_title": "Cashier"},
    {"job_title": "Telecom Technician", "short_job_title": "Technician"},
    {"job_title": "Radio Technician", "short_job_title": "Technician"},
    {"job_title": "Satellite Technician", "short_job_title": "Technician"},
    {"job_title": "Network Technician", "short_job_title": "Technician"},
    {"job_title": "Broadband Technician", "short_job_title": "Technician"},
    {"job_title": "Field Service Technician", "short_job_title": "Technician"},
    {"job_title": "Truck Driver", "short_job_title": "Driver"},
    {"job_title": "Delivery Driver", "short_job_title": "Driver"},
    {"job_title": "Taxi Driver", "short_job_title": "Driver"},
    {"job_title": "Bus Driver", "short_job_title": "Driver"},
    {"job_title": "Chauffeur", "short_job_title": "Driver"},
    {"job_title": "Forklift Driver", "short_job_title": "Driver"},
    {"job_title": "Utility Technician", "short_job_title": "Technician"},
    {"job_title": "Water Utility Worker", "short_job_title": "Technician"},
    {"job_title": "Electric Utility Worker", "short_job_title": "Technician"},
    {"job_title": "Gas Utility Worker", "short_job_title": "Technician"},
    {"job_title": "Wastewater Technician", "short_job_title": "Technician"},
    {"job_title": "Utility Line Worker", "short_job_title": "Technician"},
    {"job_title": "Venture Capital Analyst", "short_job_title": "Analyst"},
    {"job_title": "Investment Analyst", "short_job_title": "Analyst"},
    {"job_title": "Financial Analyst", "short_job_title": "Analyst"},
    {"job_title": "Private Equity Analyst", "short_job_title": "Analyst"},
    {"job_title": "Risk Analyst", "short_job_title": "Analyst"},
    {"job_title": "Equity Research Analyst", "short_job_title": "Analyst"},
    {"job_title": "Wholesale Salesperson", "short_job_title": "Salesperson"},
    {"job_title": "Wholesale Account Manager", "short_job_title": "Salesperson"},
    {"job_title": "Wholesale Buyer", "short_job_title": "Salesperson"},
    {"job_title": "Wholesale Supplier", "short_job_title": "Salesperson"},
    {"job_title": "Wholesale Distributor", "short_job_title": "Salesperson"},
    {"job_title": "Wholesale Representative", "short_job_title": "Salesperson"},
    {"job_title": "Renewable Energy Engineer", "short_job_title": "Engineer"},
    {"job_title": "Solar Engineer", "short_job_title": "Engineer"},
    {"job_title": "Wind Energy Engineer", "short_job_title": "Engineer"},
    {"job_title": "Hydropower Engineer", "short_job_title": "Engineer"},
    {"job_title": "Bioenergy Engineer", "short_job_title": "Engineer"},
    {"job_title": "Geothermal Engineer", "short_job_title": "Engineer"},
    {"job_title": "Advertising Marketer", "short_job_title": "Marketer"},
    {"job_title": "Digital Marketer", "short_job_title": "Marketer"},
    {"job_title": "Content Marketer", "short_job_title": "Marketer"},
    {"job_title": "Social Media Marketer", "short_job_title": "Marketer"},
    {"job_title": "Inbound Marketer", "short_job_title": "Marketer"},
    {"job_title": "Outbound Marketer", "short_job_title": "Marketer"},
]

# random skills

skill_jobs = [
    {"job_title": "Financial Analyst", "skill_name": "Financial Analysis"},
    {"job_title": "Financial Analyst", "skill_name": "Excel"},
    {"job_title": "Financial Analyst", "skill_name": "Data Analysis"},
    {"job_title": "Market Research Analyst", "skill_name": "Market Research"},
    {"job_title": "Market Research Analyst", "skill_name": "Data Analysis"},
    {"job_title": "Market Research Analyst", "skill_name": "Statistics"},
    {"job_title": "Data Analyst", "skill_name": "Data Analysis"},
    {"job_title": "Data Analyst", "skill_name": "SQL"},
    {"job_title": "Data Analyst", "skill_name": "Python"},
    {"job_title": "Business Analyst", "skill_name": "Business Analysis"},
    {"job_title": "Business Analyst", "skill_name": "Requirements Gathering"},
    {"job_title": "Business Analyst", "skill_name": "SQL"},
    {"job_title": "Operations Analyst", "skill_name": "Operations Management"},
    {"job_title": "Operations Analyst", "skill_name": "Data Analysis"},
    {"job_title": "Operations Analyst", "skill_name": "Process Improvement"},
    {"job_title": "Investment Analyst", "skill_name": "Investment Analysis"},
    {"job_title": "Investment Analyst", "skill_name": "Financial Modeling"},
    {"job_title": "Investment Analyst", "skill_name": "Market Research"},
    {"job_title": "Software Engineer", "skill_name": "Software Development"},
    {"job_title": "Software Engineer", "skill_name": "Programming"},
    {"job_title": "Software Engineer", "skill_name": "System Design"},
    {"job_title": "Mechanical Engineer", "skill_name": "Mechanical Design"},
    {"job_title": "Mechanical Engineer", "skill_name": "CAD"},
    {"job_title": "Mechanical Engineer", "skill_name": "Thermodynamics"},
    {"job_title": "Electrical Engineer", "skill_name": "Electrical Design"},
    {"job_title": "Electrical Engineer", "skill_name": "Circuit Analysis"},
    {"job_title": "Electrical Engineer", "skill_name": "Electronics"},
    {"job_title": "Civil Engineer", "skill_name": "Structural Engineering"},
    {"job_title": "Civil Engineer", "skill_name": "Project Management"},
    {"job_title": "Civil Engineer", "skill_name": "AutoCAD"},
    {"job_title": "Chemical Engineer", "skill_name": "Chemical Processes"},
    {"job_title": "Chemical Engineer", "skill_name": "Process Design"},
    {"job_title": "Chemical Engineer", "skill_name": "Lab Skills"},
    {
        "job_title": "Environmental Engineer",
        "skill_name": "Environmental Impact Assessment",
    },
    {"job_title": "Environmental Engineer", "skill_name": "Water Treatment"},
    {"job_title": "Environmental Engineer", "skill_name": "Sustainability"},
    {"job_title": "Lab Technician", "skill_name": "Lab Skills"},
    {"job_title": "Lab Technician", "skill_name": "Data Recording"},
    {"job_title": "Lab Technician", "skill_name": "Equipment Maintenance"},
    {"job_title": "IT Technician", "skill_name": "Hardware Troubleshooting"},
    {"job_title": "IT Technician", "skill_name": "Software Installation"},
    {"job_title": "IT Technician", "skill_name": "Network Support"},
    {"job_title": "Maintenance Technician", "skill_name": "Preventive Maintenance"},
    {"job_title": "Maintenance Technician", "skill_name": "Equipment Repair"},
    {"job_title": "Maintenance Technician", "skill_name": "Technical Skills"},
    {"job_title": "Electrical Technician", "skill_name": "Circuit Troubleshooting"},
    {"job_title": "Electrical Technician", "skill_name": "Electrical Repair"},
    {"job_title": "Electrical Technician", "skill_name": "Soldering"},
    {"job_title": "Mechanical Technician", "skill_name": "Mechanical Repair"},
    {"job_title": "Mechanical Technician", "skill_name": "Machining"},
    {"job_title": "Mechanical Technician", "skill_name": "Blueprint Reading"},
    {"job_title": "Network Technician", "skill_name": "Network Troubleshooting"},
    {"job_title": "Network Technician", "skill_name": "Cabling"},
    {"job_title": "Network Technician", "skill_name": "Router Configuration"},
    {"job_title": "Project Manager", "skill_name": "Project Planning"},
    {"job_title": "Project Manager", "skill_name": "Team Leadership"},
    {"job_title": "Project Manager", "skill_name": "Risk Management"},
    {"job_title": "Operations Manager", "skill_name": "Operations Management"},
    {"job_title": "Operations Manager", "skill_name": "Process Improvement"},
    {"job_title": "Operations Manager", "skill_name": "Leadership"},
    {"job_title": "Product Manager", "skill_name": "Product Development"},
    {"job_title": "Product Manager", "skill_name": "Market Analysis"},
    {"job_title": "Product Manager", "skill_name": "Project Management"},
    {"job_title": "Sales Manager", "skill_name": "Sales Strategy"},
    {"job_title": "Sales Manager", "skill_name": "Team Management"},
    {"job_title": "Sales Manager", "skill_name": "Customer Relationship Management"},
    {"job_title": "Marketing Manager", "skill_name": "Marketing Strategy"},
    {"job_title": "Marketing Manager", "skill_name": "Brand Management"},
    {"job_title": "Marketing Manager", "skill_name": "Digital Marketing"},
    {"job_title": "Human Resources Manager", "skill_name": "Recruitment"},
    {"job_title": "Human Resources Manager", "skill_name": "Employee Relations"},
    {"job_title": "Human Resources Manager", "skill_name": "Performance Management"},
    {"job_title": "Medical Researcher", "skill_name": "Clinical Research"},
    {"job_title": "Medical Researcher", "skill_name": "Data Analysis"},
    {"job_title": "Medical Researcher", "skill_name": "Lab Skills"},
    {"job_title": "Scientific Researcher", "skill_name": "Experimental Design"},
    {"job_title": "Scientific Researcher", "skill_name": "Data Analysis"},
    {"job_title": "Scientific Researcher", "skill_name": "Scientific Writing"},
    {"job_title": "Market Researcher", "skill_name": "Market Analysis"},
    {"job_title": "Market Researcher", "skill_name": "Survey Design"},
    {"job_title": "Market Researcher", "skill_name": "Data Collection"},
    {"job_title": "Field Researcher", "skill_name": "Field Data Collection"},
    {"job_title": "Field Researcher", "skill_name": "Survey Design"},
    {"job_title": "Field Researcher", "skill_name": "Observation"},
    {"job_title": "Policy Researcher", "skill_name": "Policy Analysis"},
    {"job_title": "Policy Researcher", "skill_name": "Research Methods"},
    {"job_title": "Policy Researcher", "skill_name": "Report Writing"},
    {"job_title": "Social Science Researcher", "skill_name": "Qualitative Research"},
    {"job_title": "Social Science Researcher", "skill_name": "Quantitative Research"},
    {"job_title": "Social Science Researcher", "skill_name": "Data Analysis"},
    {"job_title": "Construction Supervisor", "skill_name": "Construction Management"},
    {"job_title": "Construction Supervisor", "skill_name": "Blueprint Reading"},
    {"job_title": "Construction Supervisor", "skill_name": "Team Leadership"},
    {"job_title": "Manufacturing Supervisor", "skill_name": "Production Planning"},
    {"job_title": "Manufacturing Supervisor", "skill_name": "Quality Control"},
    {"job_title": "Manufacturing Supervisor", "skill_name": "Team Management"},
    {"job_title": "Maintenance Supervisor", "skill_name": "Maintenance Planning"},
    {"job_title": "Maintenance Supervisor", "skill_name": "Team Leadership"},
    {"job_title": "Maintenance Supervisor", "skill_name": "Preventive Maintenance"},
    {"job_title": "Logistics Supervisor", "skill_name": "Logistics Coordination"},
    {"job_title": "Logistics Supervisor", "skill_name": "Inventory Management"},
    {"job_title": "Logistics Supervisor", "skill_name": "Team Management"},
    {"job_title": "Production Supervisor", "skill_name": "Production Management"},
    {"job_title": "Production Supervisor", "skill_name": "Quality Control"},
    {"job_title": "Production Supervisor", "skill_name": "Team Leadership"},
    {"job_title": "Retail Supervisor", "skill_name": "Retail Management"},
    {"job_title": "Retail Supervisor", "skill_name": "Customer Service"},
    {"job_title": "Retail Supervisor", "skill_name": "Team Leadership"},
    {"job_title": "Graphic Designer", "skill_name": "Graphic Design"},
    {"job_title": "Graphic Designer", "skill_name": "Adobe Creative Suite"},
    {"job_title": "Graphic Designer", "skill_name": "Typography"},
    {"job_title": "Interior Designer", "skill_name": "Interior Design"},
    {"job_title": "Interior Designer", "skill_name": "Space Planning"},
    {"job_title": "Interior Designer", "skill_name": "CAD"},
    {"job_title": "Product Designer", "skill_name": "Product Design"},
    {"job_title": "Product Designer", "skill_name": "CAD"},
    {"job_title": "Product Designer", "skill_name": "Prototyping"},
    {"job_title": "Web Designer", "skill_name": "Web Design"},
    {"job_title": "Web Designer", "skill_name": "HTML/CSS"},
    {"job_title": "Web Designer", "skill_name": "User Experience (UX)"},
    {"job_title": "Fashion Designer", "skill_name": "Fashion Design"},
    {"job_title": "Fashion Designer", "skill_name": "Pattern Making"},
    {"job_title": "Fashion Designer", "skill_name": "Textile Knowledge"},
    {"job_title": "UX/UI Designer", "skill_name": "User Experience (UX)"},
    {"job_title": "UX/UI Designer", "skill_name": "User Interface (UI)"},
    {"job_title": "UX/UI Designer", "skill_name": "Wireframing"},
    {"job_title": "Customer Support Specialist", "skill_name": "Customer Service"},
    {"job_title": "Customer Support Specialist", "skill_name": "Problem Solving"},
    {"job_title": "Customer Support Specialist", "skill_name": "Communication"},
    {"job_title": "IT Support Specialist", "skill_name": "Technical Support"},
    {"job_title": "IT Support Specialist", "skill_name": "Troubleshooting"},
    {"job_title": "IT Support Specialist", "skill_name": "Customer Service"},
    {"job_title": "Marketing Specialist", "skill_name": "Marketing Strategy"},
    {"job_title": "Marketing Specialist", "skill_name": "Content Creation"},
    {"job_title": "Marketing Specialist", "skill_name": "SEO"},
    {"job_title": "HR Specialist", "skill_name": "Recruitment"},
    {"job_title": "HR Specialist", "skill_name": "Employee Relations"},
    {"job_title": "HR Specialist", "skill_name": "HR Policies"},
    {"job_title": "Financial Specialist", "skill_name": "Financial Analysis"},
    {"job_title": "Financial Specialist", "skill_name": "Budgeting"},
    {"job_title": "Financial Specialist", "skill_name": "Accounting"},
    {"job_title": "Sales Specialist", "skill_name": "Sales Strategy"},
    {"job_title": "Sales Specialist", "skill_name": "Customer Relationship Management"},
    {"job_title": "Sales Specialist", "skill_name": "Negotiation"},
    {"job_title": "Elementary School Teacher", "skill_name": "Classroom Management"},
    {"job_title": "Elementary School Teacher", "skill_name": "Lesson Planning"},
    {"job_title": "Elementary School Teacher", "skill_name": "Child Development"},
    {"job_title": "High School Teacher", "skill_name": "Subject Matter Expertise"},
    {"job_title": "High School Teacher", "skill_name": "Classroom Management"},
    {"job_title": "High School Teacher", "skill_name": "Lesson Planning"},
    {"job_title": "Special Education Teacher", "skill_name": "Special Education"},
    {"job_title": "Special Education Teacher", "skill_name": "IEP Development"},
    {"job_title": "Special Education Teacher", "skill_name": "Behavior Management"},
    {"job_title": "ESL Teacher", "skill_name": "ESL Instruction"},
    {"job_title": "ESL Teacher", "skill_name": "Language Proficiency Assessment"},
    {"job_title": "ESL Teacher", "skill_name": "Cultural Sensitivity"},
    {"job_title": "Substitute Teacher", "skill_name": "Classroom Management"},
    {"job_title": "Substitute Teacher", "skill_name": "Lesson Implementation"},
    {"job_title": "Substitute Teacher", "skill_name": "Flexibility"},
    {"job_title": "Kindergarten Teacher", "skill_name": "Early Childhood Education"},
    {"job_title": "Kindergarten Teacher", "skill_name": "Classroom Management"},
    {"job_title": "Kindergarten Teacher", "skill_name": "Child Development"},
    {"job_title": "Business Consultant", "skill_name": "Business Strategy"},
    {"job_title": "Business Consultant", "skill_name": "Market Analysis"},
    {"job_title": "Business Consultant", "skill_name": "Client Management"},
    {"job_title": "Financial Consultant", "skill_name": "Financial Planning"},
    {"job_title": "Financial Consultant", "skill_name": "Investment Strategies"},
    {"job_title": "Financial Consultant", "skill_name": "Client Management"},
    {"job_title": "IT Consultant", "skill_name": "IT Strategy"},
    {"job_title": "IT Consultant", "skill_name": "Systems Analysis"},
    {"job_title": "IT Consultant", "skill_name": "Client Management"},
    {"job_title": "Management Consultant", "skill_name": "Business Strategy"},
    {"job_title": "Management Consultant", "skill_name": "Process Improvement"},
    {"job_title": "Management Consultant", "skill_name": "Client Management"},
    {"job_title": "HR Consultant", "skill_name": "HR Strategy"},
    {"job_title": "HR Consultant", "skill_name": "Recruitment"},
    {"job_title": "HR Consultant", "skill_name": "Employee Relations"},
    {"job_title": "Strategy Consultant", "skill_name": "Business Strategy"},
    {"job_title": "Strategy Consultant", "skill_name": "Market Analysis"},
    {"job_title": "Strategy Consultant", "skill_name": "Data Analysis"},
    {"job_title": "Film Producer", "skill_name": "Film Production"},
    {"job_title": "Film Producer", "skill_name": "Budget Management"},
    {"job_title": "Film Producer", "skill_name": "Team Coordination"},
    {"job_title": "Music Producer", "skill_name": "Music Production"},
    {"job_title": "Music Producer", "skill_name": "Audio Engineering"},
    {"job_title": "Music Producer", "skill_name": "Artist Management"},
    {"job_title": "Television Producer", "skill_name": "TV Production"},
    {"job_title": "Television Producer", "skill_name": "Budget Management"},
    {"job_title": "Television Producer", "skill_name": "Team Coordination"},
    {"job_title": "Theater Producer", "skill_name": "Theater Production"},
    {"job_title": "Theater Producer", "skill_name": "Budget Management"},
    {"job_title": "Theater Producer", "skill_name": "Team Coordination"},
    {"job_title": "Video Producer", "skill_name": "Video Production"},
    {"job_title": "Video Producer", "skill_name": "Editing"},
    {"job_title": "Video Producer", "skill_name": "Project Management"},
    {"job_title": "Event Producer", "skill_name": "Event Planning"},
    {"job_title": "Event Producer", "skill_name": "Budget Management"},
    {"job_title": "Event Producer", "skill_name": "Vendor Coordination"},
    {"job_title": "Hair Stylist", "skill_name": "Hair Cutting"},
    {"job_title": "Hair Stylist", "skill_name": "Hair Coloring"},
    {"job_title": "Hair Stylist", "skill_name": "Customer Service"},
    {"job_title": "Fashion Stylist", "skill_name": "Fashion Trends"},
    {"job_title": "Fashion Stylist", "skill_name": "Wardrobe Planning"},
    {"job_title": "Fashion Stylist", "skill_name": "Client Consultation"},
    {"job_title": "Wardrobe Stylist", "skill_name": "Wardrobe Planning"},
    {"job_title": "Wardrobe Stylist", "skill_name": "Fashion Trends"},
    {"job_title": "Wardrobe Stylist", "skill_name": "Client Consultation"},
    {"job_title": "Makeup Stylist", "skill_name": "Makeup Application"},
    {"job_title": "Makeup Stylist", "skill_name": "Color Theory"},
    {"job_title": "Makeup Stylist", "skill_name": "Customer Service"},
    {"job_title": "Interior Stylist", "skill_name": "Interior Design"},
    {"job_title": "Interior Stylist", "skill_name": "Space Planning"},
    {"job_title": "Interior Stylist", "skill_name": "Client Consultation"},
    {"job_title": "Personal Stylist", "skill_name": "Fashion Trends"},
    {"job_title": "Personal Stylist", "skill_name": "Wardrobe Planning"},
    {"job_title": "Personal Stylist", "skill_name": "Client Consultation"},
    {"job_title": "Financial Advisor", "skill_name": "Financial Planning"},
    {"job_title": "Financial Advisor", "skill_name": "Investment Strategies"},
    {"job_title": "Financial Advisor", "skill_name": "Client Management"},
    {"job_title": "Career Advisor", "skill_name": "Career Counseling"},
    {"job_title": "Career Advisor", "skill_name": "Resume Writing"},
    {"job_title": "Career Advisor", "skill_name": "Job Search Strategies"},
    {"job_title": "Academic Advisor", "skill_name": "Academic Counseling"},
    {"job_title": "Academic Advisor", "skill_name": "Course Planning"},
    {"job_title": "Academic Advisor", "skill_name": "Student Support"},
    {"job_title": "Legal Advisor", "skill_name": "Legal Knowledge"},
    {"job_title": "Legal Advisor", "skill_name": "Client Consultation"},
    {"job_title": "Legal Advisor", "skill_name": "Research"},
    {"job_title": "Customer Service Advisor", "skill_name": "Customer Service"},
    {"job_title": "Customer Service Advisor", "skill_name": "Problem Solving"},
    {"job_title": "Customer Service Advisor", "skill_name": "Communication"},
    {"job_title": "Investment Advisor", "skill_name": "Investment Strategies"},
    {"job_title": "Investment Advisor", "skill_name": "Financial Planning"},
    {"job_title": "Investment Advisor", "skill_name": "Client Management"},
    {"job_title": "Executive Chef", "skill_name": "Culinary Skills"},
    {"job_title": "Executive Chef", "skill_name": "Menu Planning"},
    {"job_title": "Executive Chef", "skill_name": "Kitchen Management"},
    {"job_title": "Sous Chef", "skill_name": "Culinary Skills"},
    {"job_title": "Sous Chef", "skill_name": "Team Leadership"},
    {"job_title": "Sous Chef", "skill_name": "Food Preparation"},
    {"job_title": "Pastry Chef", "skill_name": "Baking"},
    {"job_title": "Pastry Chef", "skill_name": "Pastry Making"},
    {"job_title": "Pastry Chef", "skill_name": "Creativity"},
    {"job_title": "Line Chef", "skill_name": "Food Preparation"},
    {"job_title": "Line Chef", "skill_name": "Cooking"},
    {"job_title": "Line Chef", "skill_name": "Teamwork"},
    {"job_title": "Personal Chef", "skill_name": "Culinary Skills"},
    {"job_title": "Personal Chef", "skill_name": "Menu Planning"},
    {"job_title": "Personal Chef", "skill_name": "Client Interaction"},
    {"job_title": "Banquet Chef", "skill_name": "Culinary Skills"},
    {"job_title": "Banquet Chef", "skill_name": "Event Planning"},
    {"job_title": "Banquet Chef", "skill_name": "Team Coordination"},
    {"job_title": "Registered Nurse", "skill_name": "Patient Care"},
    {"job_title": "Registered Nurse", "skill_name": "Clinical Skills"},
    {"job_title": "Registered Nurse", "skill_name": "Medical Knowledge"},
    {"job_title": "Nurse Practitioner", "skill_name": "Patient Care"},
    {"job_title": "Nurse Practitioner", "skill_name": "Clinical Skills"},
    {"job_title": "Nurse Practitioner", "skill_name": "Medical Knowledge"},
    {"job_title": "Clinical Nurse", "skill_name": "Patient Care"},
    {"job_title": "Clinical Nurse", "skill_name": "Clinical Skills"},
    {"job_title": "Clinical Nurse", "skill_name": "Medical Knowledge"},
    {"job_title": "Pediatric Nurse", "skill_name": "Pediatric Care"},
    {"job_title": "Pediatric Nurse", "skill_name": "Clinical Skills"},
    {"job_title": "Pediatric Nurse", "skill_name": "Medical Knowledge"},
    {"job_title": "ER Nurse", "skill_name": "Emergency Care"},
    {"job_title": "ER Nurse", "skill_name": "Clinical Skills"},
    {"job_title": "ER Nurse", "skill_name": "Medical Knowledge"},
    {"job_title": "Surgical Nurse", "skill_name": "Surgical Assistance"},
    {"job_title": "Surgical Nurse", "skill_name": "Patient Care"},
    {"job_title": "Surgical Nurse", "skill_name": "Clinical Skills"},
    {"job_title": "Front Desk Receptionist", "skill_name": "Customer Service"},
    {"job_title": "Front Desk Receptionist", "skill_name": "Communication"},
    {"job_title": "Front Desk Receptionist", "skill_name": "Administrative Skills"},
    {"job_title": "Medical Receptionist", "skill_name": "Customer Service"},
    {"job_title": "Medical Receptionist", "skill_name": "Medical Terminology"},
    {"job_title": "Medical Receptionist", "skill_name": "Administrative Skills"},
    {"job_title": "Dental Receptionist", "skill_name": "Customer Service"},
    {"job_title": "Dental Receptionist", "skill_name": "Dental Terminology"},
    {"job_title": "Dental Receptionist", "skill_name": "Administrative Skills"},
    {"job_title": "Hotel Receptionist", "skill_name": "Customer Service"},
    {"job_title": "Hotel Receptionist", "skill_name": "Booking Systems"},
    {"job_title": "Hotel Receptionist", "skill_name": "Communication"},
    {"job_title": "Corporate Receptionist", "skill_name": "Customer Service"},
    {"job_title": "Corporate Receptionist", "skill_name": "Administrative Skills"},
    {"job_title": "Corporate Receptionist", "skill_name": "Communication"},
    {"job_title": "Salon Receptionist", "skill_name": "Customer Service"},
    {"job_title": "Salon Receptionist", "skill_name": "Booking Systems"},
    {"job_title": "Salon Receptionist", "skill_name": "Administrative Skills"},
    {"job_title": "Software Developer", "skill_name": "Programming"},
    {"job_title": "Software Developer", "skill_name": "Software Design"},
    {"job_title": "Software Developer", "skill_name": "Problem Solving"},
    {"job_title": "Web Developer", "skill_name": "Web Development"},
    {"job_title": "Web Developer", "skill_name": "HTML/CSS"},
    {"job_title": "Web Developer", "skill_name": "JavaScript"},
    {"job_title": "Mobile App Developer", "skill_name": "Mobile Development"},
    {"job_title": "Mobile App Developer", "skill_name": "iOS/Android"},
    {"job_title": "Mobile App Developer", "skill_name": "Programming"},
    {"job_title": "Game Developer", "skill_name": "Game Development"},
    {"job_title": "Game Developer", "skill_name": "Programming"},
    {"job_title": "Game Developer", "skill_name": "Graphics"},
    {"job_title": "Frontend Developer", "skill_name": "Frontend Development"},
    {"job_title": "Frontend Developer", "skill_name": "HTML/CSS"},
    {"job_title": "Frontend Developer", "skill_name": "JavaScript"},
    {"job_title": "Backend Developer", "skill_name": "Backend Development"},
    {"job_title": "Backend Developer", "skill_name": "Database Management"},
    {"job_title": "Backend Developer", "skill_name": "API Design"},
    {"job_title": "Insurance Underwriter", "skill_name": "Risk Assessment"},
    {"job_title": "Insurance Underwriter", "skill_name": "Insurance Knowledge"},
    {"job_title": "Insurance Underwriter", "skill_name": "Analytical Skills"},
    {"job_title": "Loan Underwriter", "skill_name": "Risk Assessment"},
    {"job_title": "Loan Underwriter", "skill_name": "Financial Analysis"},
    {"job_title": "Loan Underwriter", "skill_name": "Loan Processing"},
    {"job_title": "Mortgage Underwriter", "skill_name": "Risk Assessment"},
    {"job_title": "Mortgage Underwriter", "skill_name": "Mortgage Knowledge"},
    {"job_title": "Mortgage Underwriter", "skill_name": "Financial Analysis"},
    {"job_title": "Health Insurance Underwriter", "skill_name": "Risk Assessment"},
    {
        "job_title": "Health Insurance Underwriter",
        "skill_name": "Health Insurance Knowledge",
    },
    {"job_title": "Health Insurance Underwriter", "skill_name": "Analytical Skills"},
    {"job_title": "Life Insurance Underwriter", "skill_name": "Risk Assessment"},
    {
        "job_title": "Life Insurance Underwriter",
        "skill_name": "Life Insurance Knowledge",
    },
    {"job_title": "Life Insurance Underwriter", "skill_name": "Analytical Skills"},
    {"job_title": "Property and Casualty Underwriter", "skill_name": "Risk Assessment"},
    {
        "job_title": "Property and Casualty Underwriter",
        "skill_name": "Property and Casualty Knowledge",
    },
    {
        "job_title": "Property and Casualty Underwriter",
        "skill_name": "Analytical Skills",
    },
    {"job_title": "Corporate Paralegal", "skill_name": "Legal Knowledge"},
    {"job_title": "Corporate Paralegal", "skill_name": "Document Preparation"},
    {"job_title": "Corporate Paralegal", "skill_name": "Research"},
    {"job_title": "Litigation Paralegal", "skill_name": "Legal Knowledge"},
    {"job_title": "Litigation Paralegal", "skill_name": "Case Management"},
    {"job_title": "Litigation Paralegal", "skill_name": "Research"},
    {"job_title": "Immigration Paralegal", "skill_name": "Immigration Law"},
    {"job_title": "Immigration Paralegal", "skill_name": "Document Preparation"},
    {"job_title": "Immigration Paralegal", "skill_name": "Client Interaction"},
    {"job_title": "Real Estate Paralegal", "skill_name": "Real Estate Law"},
    {"job_title": "Real Estate Paralegal", "skill_name": "Document Preparation"},
    {"job_title": "Real Estate Paralegal", "skill_name": "Research"},
    {"job_title": "Family Law Paralegal", "skill_name": "Family Law"},
    {"job_title": "Family Law Paralegal", "skill_name": "Document Preparation"},
    {"job_title": "Family Law Paralegal", "skill_name": "Client Interaction"},
    {"job_title": "IP Paralegal", "skill_name": "Intellectual Property Law"},
    {"job_title": "IP Paralegal", "skill_name": "Document Preparation"},
    {"job_title": "IP Paralegal", "skill_name": "Research"},
    {"job_title": "Logistics Coordinator", "skill_name": "Logistics Management"},
    {"job_title": "Logistics Coordinator", "skill_name": "Inventory Management"},
    {"job_title": "Logistics Coordinator", "skill_name": "Supply Chain Knowledge"},
    {"job_title": "Project Coordinator", "skill_name": "Project Management"},
    {"job_title": "Project Coordinator", "skill_name": "Team Coordination"},
    {"job_title": "Project Coordinator", "skill_name": "Communication"},
    {"job_title": "Event Coordinator", "skill_name": "Event Planning"},
    {"job_title": "Event Coordinator", "skill_name": "Vendor Coordination"},
    {"job_title": "Event Coordinator", "skill_name": "Communication"},
    {"job_title": "Marketing Coordinator", "skill_name": "Marketing Strategy"},
    {"job_title": "Marketing Coordinator", "skill_name": "Content Creation"},
    {"job_title": "Marketing Coordinator", "skill_name": "Social Media"},
    {"job_title": "Sales Coordinator", "skill_name": "Sales Strategy"},
    {
        "job_title": "Sales Coordinator",
        "skill_name": "Customer Relationship Management",
    },
    {"job_title": "Sales Coordinator", "skill_name": "Communication"},
    {"job_title": "HR Coordinator", "skill_name": "Recruitment"},
    {"job_title": "HR Coordinator", "skill_name": "Employee Relations"},
    {"job_title": "HR Coordinator", "skill_name": "HR Policies"},
    {"job_title": "Machine Operator", "skill_name": "Machine Operation"},
    {"job_title": "Machine Operator", "skill_name": "Safety Procedures"},
    {"job_title": "Machine Operator", "skill_name": "Technical Skills"},
    {
        "job_title": "Heavy Equipment Operator",
        "skill_name": "Heavy Equipment Operation",
    },
    {"job_title": "Heavy Equipment Operator", "skill_name": "Safety Procedures"},
    {"job_title": "Heavy Equipment Operator", "skill_name": "Technical Skills"},
    {"job_title": "Crane Operator", "skill_name": "Crane Operation"},
    {"job_title": "Crane Operator", "skill_name": "Safety Procedures"},
    {"job_title": "Crane Operator", "skill_name": "Technical Skills"},
    {"job_title": "Forklift Operator", "skill_name": "Forklift Operation"},
    {"job_title": "Forklift Operator", "skill_name": "Safety Procedures"},
    {"job_title": "Forklift Operator", "skill_name": "Technical Skills"},
    {"job_title": "Plant Operator", "skill_name": "Plant Operation"},
    {"job_title": "Plant Operator", "skill_name": "Safety Procedures"},
    {"job_title": "Plant Operator", "skill_name": "Technical Skills"},
    {"job_title": "Production Operator", "skill_name": "Production Management"},
    {"job_title": "Production Operator", "skill_name": "Quality Control"},
    {"job_title": "Production Operator", "skill_name": "Technical Skills"},
    {"job_title": "News Journalist", "skill_name": "Journalism"},
    {"job_title": "News Journalist", "skill_name": "Writing"},
    {"job_title": "News Journalist", "skill_name": "Research"},
    {"job_title": "Broadcast Journalist", "skill_name": "Journalism"},
    {"job_title": "Broadcast Journalist", "skill_name": "Broadcasting"},
    {"job_title": "Broadcast Journalist", "skill_name": "Research"},
    {"job_title": "Sports Journalist", "skill_name": "Journalism"},
    {"job_title": "Sports Journalist", "skill_name": "Sports Knowledge"},
    {"job_title": "Sports Journalist", "skill_name": "Writing"},
    {"job_title": "Investigative Journalist", "skill_name": "Investigative Reporting"},
    {"job_title": "Investigative Journalist", "skill_name": "Research"},
    {"job_title": "Investigative Journalist", "skill_name": "Writing"},
    {"job_title": "Freelance Journalist", "skill_name": "Journalism"},
    {"job_title": "Freelance Journalist", "skill_name": "Writing"},
    {"job_title": "Freelance Journalist", "skill_name": "Research"},
    {"job_title": "Photojournalist", "skill_name": "Photography"},
    {"job_title": "Photojournalist", "skill_name": "Journalism"},
    {"job_title": "Photojournalist", "skill_name": "Photo Editing"},
    {"job_title": "Field Geologist", "skill_name": "Geology"},
    {"job_title": "Field Geologist", "skill_name": "Field Work"},
    {"job_title": "Field Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Environmental Geologist", "skill_name": "Environmental Science"},
    {"job_title": "Environmental Geologist", "skill_name": "Geology"},
    {"job_title": "Environmental Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Petroleum Geologist", "skill_name": "Geology"},
    {"job_title": "Petroleum Geologist", "skill_name": "Petroleum Engineering"},
    {"job_title": "Petroleum Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Mining Geologist", "skill_name": "Geology"},
    {"job_title": "Mining Geologist", "skill_name": "Mining Engineering"},
    {"job_title": "Mining Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Engineering Geologist", "skill_name": "Geology"},
    {"job_title": "Engineering Geologist", "skill_name": "Engineering"},
    {"job_title": "Engineering Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Hydrogeologist", "skill_name": "Hydrogeology"},
    {"job_title": "Hydrogeologist", "skill_name": "Water Resource Management"},
    {"job_title": "Hydrogeologist", "skill_name": "Data Analysis"},
    {"job_title": "Executive Director", "skill_name": "Leadership"},
    {"job_title": "Executive Director", "skill_name": "Strategic Planning"},
    {"job_title": "Executive Director", "skill_name": "Financial Management"},
    {"job_title": "Program Director", "skill_name": "Program Management"},
    {"job_title": "Program Director", "skill_name": "Strategic Planning"},
    {"job_title": "Program Director", "skill_name": "Team Leadership"},
    {"job_title": "Creative Director", "skill_name": "Creative Direction"},
    {"job_title": "Creative Director", "skill_name": "Team Leadership"},
    {"job_title": "Creative Director", "skill_name": "Project Management"},
    {"job_title": "Marketing Director", "skill_name": "Marketing Strategy"},
    {"job_title": "Marketing Director", "skill_name": "Team Leadership"},
    {"job_title": "Marketing Director", "skill_name": "Brand Management"},
    {"job_title": "Technical Director", "skill_name": "Technical Expertise"},
    {"job_title": "Technical Director", "skill_name": "Team Leadership"},
    {"job_title": "Technical Director", "skill_name": "Project Management"},
    {"job_title": "Art Director", "skill_name": "Art Direction"},
    {"job_title": "Art Director", "skill_name": "Design"},
    {"job_title": "Art Director", "skill_name": "Project Management"},
    {"job_title": "Oil and Gas Geologist", "skill_name": "Geology"},
    {"job_title": "Oil and Gas Geologist", "skill_name": "Petroleum Engineering"},
    {"job_title": "Oil and Gas Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Reservoir Geologist", "skill_name": "Geology"},
    {"job_title": "Reservoir Geologist", "skill_name": "Reservoir Engineering"},
    {"job_title": "Reservoir Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Production Geologist", "skill_name": "Geology"},
    {"job_title": "Production Geologist", "skill_name": "Production Engineering"},
    {"job_title": "Production Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Exploration Geologist", "skill_name": "Geology"},
    {"job_title": "Exploration Geologist", "skill_name": "Exploration Techniques"},
    {"job_title": "Exploration Geologist", "skill_name": "Data Analysis"},
    {"job_title": "Petrophysicist", "skill_name": "Petrophysics"},
    {"job_title": "Petrophysicist", "skill_name": "Geology"},
    {"job_title": "Petrophysicist", "skill_name": "Data Analysis"},
    {"job_title": "Mud Logger", "skill_name": "Mud Logging"},
    {"job_title": "Mud Logger", "skill_name": "Geology"},
    {"job_title": "Mud Logger", "skill_name": "Data Analysis"},
    {"job_title": "Clinical Pharmacist", "skill_name": "Pharmacy"},
    {"job_title": "Clinical Pharmacist", "skill_name": "Clinical Knowledge"},
    {"job_title": "Clinical Pharmacist", "skill_name": "Patient Care"},
    {"job_title": "Retail Pharmacist", "skill_name": "Pharmacy"},
    {"job_title": "Retail Pharmacist", "skill_name": "Customer Service"},
    {"job_title": "Retail Pharmacist", "skill_name": "Medication Management"},
    {"job_title": "Hospital Pharmacist", "skill_name": "Pharmacy"},
    {"job_title": "Hospital Pharmacist", "skill_name": "Clinical Knowledge"},
    {"job_title": "Hospital Pharmacist", "skill_name": "Patient Care"},
    {"job_title": "Research Pharmacist", "skill_name": "Pharmacy"},
    {"job_title": "Research Pharmacist", "skill_name": "Research"},
    {"job_title": "Research Pharmacist", "skill_name": "Data Analysis"},
    {"job_title": "Nuclear Pharmacist", "skill_name": "Pharmacy"},
    {"job_title": "Nuclear Pharmacist", "skill_name": "Nuclear Medicine"},
    {"job_title": "Nuclear Pharmacist", "skill_name": "Safety Procedures"},
    {"job_title": "Industrial Pharmacist", "skill_name": "Pharmacy"},
    {"job_title": "Industrial Pharmacist", "skill_name": "Manufacturing"},
    {"job_title": "Industrial Pharmacist", "skill_name": "Quality Control"},
    {"job_title": "Administrative Assistant", "skill_name": "Administrative Skills"},
    {"job_title": "Administrative Assistant", "skill_name": "Organization"},
    {"job_title": "Administrative Assistant", "skill_name": "Communication"},
    {"job_title": "Office Administrator", "skill_name": "Office Management"},
    {"job_title": "Office Administrator", "skill_name": "Organization"},
    {"job_title": "Office Administrator", "skill_name": "Communication"},
    {"job_title": "Systems Administrator", "skill_name": "System Administration"},
    {"job_title": "Systems Administrator", "skill_name": "Network Management"},
    {"job_title": "Systems Administrator", "skill_name": "Technical Support"},
    {"job_title": "Database Administrator", "skill_name": "Database Management"},
    {"job_title": "Database Administrator", "skill_name": "SQL"},
    {"job_title": "Database Administrator", "skill_name": "Performance Tuning"},
    {"job_title": "Network Administrator", "skill_name": "Network Management"},
    {"job_title": "Network Administrator", "skill_name": "Security"},
    {"job_title": "Network Administrator", "skill_name": "Troubleshooting"},
    {"job_title": "School Administrator", "skill_name": "Educational Leadership"},
    {"job_title": "School Administrator", "skill_name": "School Management"},
    {"job_title": "School Administrator", "skill_name": "Communication"},
    {"job_title": "Real Estate Agent", "skill_name": "Real Estate Knowledge"},
    {"job_title": "Real Estate Agent", "skill_name": "Sales"},
    {"job_title": "Real Estate Agent", "skill_name": "Client Relationship Management"},
    {"job_title": "Travel Agent", "skill_name": "Travel Planning"},
    {"job_title": "Travel Agent", "skill_name": "Customer Service"},
    {"job_title": "Travel Agent", "skill_name": "Sales"},
    {"job_title": "Insurance Agent", "skill_name": "Insurance Knowledge"},
    {"job_title": "Insurance Agent", "skill_name": "Sales"},
    {"job_title": "Insurance Agent", "skill_name": "Customer Service"},
    {"job_title": "Sports Agent", "skill_name": "Sports Knowledge"},
    {"job_title": "Sports Agent", "skill_name": "Contract Negotiation"},
    {"job_title": "Sports Agent", "skill_name": "Client Management"},
    {"job_title": "Talent Agent", "skill_name": "Talent Management"},
    {"job_title": "Talent Agent", "skill_name": "Contract Negotiation"},
    {"job_title": "Talent Agent", "skill_name": "Client Management"},
    {"job_title": "Customs Agent", "skill_name": "Customs Knowledge"},
    {"job_title": "Customs Agent", "skill_name": "Security Procedures"},
    {"job_title": "Customs Agent", "skill_name": "Communication"},
    {"job_title": "Retail Cashier", "skill_name": "Customer Service"},
    {"job_title": "Retail Cashier", "skill_name": "Cash Handling"},
    {"job_title": "Retail Cashier", "skill_name": "POS Systems"},
    {"job_title": "Bank Cashier", "skill_name": "Customer Service"},
    {"job_title": "Bank Cashier", "skill_name": "Cash Handling"},
    {"job_title": "Bank Cashier", "skill_name": "Financial Transactions"},
    {"job_title": "Grocery Store Cashier", "skill_name": "Customer Service"},
    {"job_title": "Grocery Store Cashier", "skill_name": "Cash Handling"},
    {"job_title": "Grocery Store Cashier", "skill_name": "POS Systems"},
    {"job_title": "Restaurant Cashier", "skill_name": "Customer Service"},
    {"job_title": "Restaurant Cashier", "skill_name": "Cash Handling"},
    {"job_title": "Restaurant Cashier", "skill_name": "POS Systems"},
    {"job_title": "Movie Theater Cashier", "skill_name": "Customer Service"},
    {"job_title": "Movie Theater Cashier", "skill_name": "Cash Handling"},
    {"job_title": "Movie Theater Cashier", "skill_name": "POS Systems"},
    {"job_title": "Parking Lot Cashier", "skill_name": "Customer Service"},
    {"job_title": "Parking Lot Cashier", "skill_name": "Cash Handling"},
    {"job_title": "Parking Lot Cashier", "skill_name": "POS Systems"},
    {"job_title": "Telecom Technician", "skill_name": "Telecommunications"},
    {"job_title": "Telecom Technician", "skill_name": "Technical Support"},
    {"job_title": "Telecom Technician", "skill_name": "Troubleshooting"},
    {"job_title": "Radio Technician", "skill_name": "Radio Equipment"},
    {"job_title": "Radio Technician", "skill_name": "Technical Support"},
    {"job_title": "Radio Technician", "skill_name": "Troubleshooting"},
    {"job_title": "Satellite Technician", "skill_name": "Satellite Equipment"},
    {"job_title": "Satellite Technician", "skill_name": "Technical Support"},
    {"job_title": "Satellite Technician", "skill_name": "Troubleshooting"},
    {"job_title": "Network Technician", "skill_name": "Network Management"},
    {"job_title": "Network Technician", "skill_name": "Technical Support"},
    {"job_title": "Network Technician", "skill_name": "Troubleshooting"},
    {"job_title": "Broadband Technician", "skill_name": "Broadband Equipment"},
    {"job_title": "Broadband Technician", "skill_name": "Technical Support"},
    {"job_title": "Broadband Technician", "skill_name": "Troubleshooting"},
    {"job_title": "Field Service Technician", "skill_name": "Field Service"},
    {"job_title": "Field Service Technician", "skill_name": "Technical Support"},
    {"job_title": "Field Service Technician", "skill_name": "Troubleshooting"},
    {"job_title": "Truck Driver", "skill_name": "Driving Skills"},
    {"job_title": "Truck Driver", "skill_name": "Route Planning"},
    {"job_title": "Truck Driver", "skill_name": "Safety Procedures"},
    {"job_title": "Delivery Driver", "skill_name": "Driving Skills"},
    {"job_title": "Delivery Driver", "skill_name": "Route Planning"},
    {"job_title": "Delivery Driver", "skill_name": "Customer Service"},
    {"job_title": "Taxi Driver", "skill_name": "Driving Skills"},
    {"job_title": "Taxi Driver", "skill_name": "Route Planning"},
    {"job_title": "Taxi Driver", "skill_name": "Customer Service"},
    {"job_title": "Bus Driver", "skill_name": "Driving Skills"},
    {"job_title": "Bus Driver", "skill_name": "Route Planning"},
    {"job_title": "Bus Driver", "skill_name": "Safety Procedures"},
    {"job_title": "Chauffeur", "skill_name": "Driving Skills"},
    {"job_title": "Chauffeur", "skill_name": "Customer Service"},
    {"job_title": "Chauffeur", "skill_name": "Route Planning"},
    {"job_title": "Forklift Driver", "skill_name": "Forklift Operation"},
    {"job_title": "Forklift Driver", "skill_name": "Safety Procedures"},
    {"job_title": "Forklift Driver", "skill_name": "Inventory Management"},
    {"job_title": "Utility Technician", "skill_name": "Utility Maintenance"},
    {"job_title": "Utility Technician", "skill_name": "Technical Skills"},
    {"job_title": "Utility Technician", "skill_name": "Safety Procedures"},
    {"job_title": "Water Utility Worker", "skill_name": "Water Systems"},
    {"job_title": "Water Utility Worker", "skill_name": "Maintenance"},
    {"job_title": "Water Utility Worker", "skill_name": "Safety Procedures"},
    {"job_title": "Electric Utility Worker", "skill_name": "Electrical Systems"},
    {"job_title": "Electric Utility Worker", "skill_name": "Maintenance"},
    {"job_title": "Electric Utility Worker", "skill_name": "Safety Procedures"},
    {"job_title": "Gas Utility Worker", "skill_name": "Gas Systems"},
    {"job_title": "Gas Utility Worker", "skill_name": "Maintenance"},
    {"job_title": "Gas Utility Worker", "skill_name": "Safety Procedures"},
    {"job_title": "Wastewater Technician", "skill_name": "Wastewater Systems"},
    {"job_title": "Wastewater Technician", "skill_name": "Maintenance"},
    {"job_title": "Wastewater Technician", "skill_name": "Safety Procedures"},
    {"job_title": "Utility Line Worker", "skill_name": "Line Maintenance"},
    {"job_title": "Utility Line Worker", "skill_name": "Technical Skills"},
    {"job_title": "Utility Line Worker", "skill_name": "Safety Procedures"},
    {"job_title": "Venture Capital Analyst", "skill_name": "Investment Analysis"},
    {"job_title": "Venture Capital Analyst", "skill_name": "Financial Modeling"},
    {"job_title": "Venture Capital Analyst", "skill_name": "Market Research"},
    {"job_title": "Private Equity Analyst", "skill_name": "Investment Analysis"},
    {"job_title": "Private Equity Analyst", "skill_name": "Financial Modeling"},
    {"job_title": "Private Equity Analyst", "skill_name": "Market Research"},
    {"job_title": "Risk Analyst", "skill_name": "Risk Assessment"},
    {"job_title": "Risk Analyst", "skill_name": "Data Analysis"},
    {"job_title": "Risk Analyst", "skill_name": "Financial Analysis"},
    {"job_title": "Equity Research Analyst", "skill_name": "Equity Research"},
    {"job_title": "Equity Research Analyst", "skill_name": "Financial Analysis"},
    {"job_title": "Equity Research Analyst", "skill_name": "Market Research"},
    {"job_title": "Wholesale Salesperson", "skill_name": "Sales"},
    {
        "job_title": "Wholesale Salesperson",
        "skill_name": "Customer Relationship Management",
    },
    {"job_title": "Wholesale Salesperson", "skill_name": "Negotiation"},
    {"job_title": "Wholesale Account Manager", "skill_name": "Account Management"},
    {"job_title": "Wholesale Account Manager", "skill_name": "Sales Strategy"},
    {
        "job_title": "Wholesale Account Manager",
        "skill_name": "Customer Relationship Management",
    },
    {"job_title": "Wholesale Buyer", "skill_name": "Purchasing"},
    {"job_title": "Wholesale Buyer", "skill_name": "Vendor Management"},
    {"job_title": "Wholesale Buyer", "skill_name": "Negotiation"},
    {"job_title": "Wholesale Supplier", "skill_name": "Supply Chain Management"},
    {"job_title": "Wholesale Supplier", "skill_name": "Vendor Management"},
    {"job_title": "Wholesale Supplier", "skill_name": "Negotiation"},
    {"job_title": "Wholesale Distributor", "skill_name": "Distribution Management"},
    {"job_title": "Wholesale Distributor", "skill_name": "Supply Chain Management"},
    {"job_title": "Wholesale Distributor", "skill_name": "Logistics"},
    {"job_title": "Wholesale Representative", "skill_name": "Sales"},
    {
        "job_title": "Wholesale Representative",
        "skill_name": "Customer Relationship Management",
    },
    {"job_title": "Wholesale Representative", "skill_name": "Negotiation"},
    {"job_title": "Renewable Energy Engineer", "skill_name": "Renewable Energy"},
    {"job_title": "Renewable Energy Engineer", "skill_name": "Engineering"},
    {"job_title": "Renewable Energy Engineer", "skill_name": "Sustainability"},
    {"job_title": "Solar Engineer", "skill_name": "Solar Energy"},
    {"job_title": "Solar Engineer", "skill_name": "Engineering"},
    {"job_title": "Solar Engineer", "skill_name": "Sustainability"},
    {"job_title": "Wind Energy Engineer", "skill_name": "Wind Energy"},
    {"job_title": "Wind Energy Engineer", "skill_name": "Engineering"},
    {"job_title": "Wind Energy Engineer", "skill_name": "Sustainability"},
    {"job_title": "Hydropower Engineer", "skill_name": "Hydropower"},
    {"job_title": "Hydropower Engineer", "skill_name": "Engineering"},
    {"job_title": "Hydropower Engineer", "skill_name": "Sustainability"},
    {"job_title": "Bioenergy Engineer", "skill_name": "Bioenergy"},
    {"job_title": "Bioenergy Engineer", "skill_name": "Engineering"},
    {"job_title": "Bioenergy Engineer", "skill_name": "Sustainability"},
    {"job_title": "Geothermal Engineer", "skill_name": "Geothermal Energy"},
    {"job_title": "Geothermal Engineer", "skill_name": "Engineering"},
    {"job_title": "Geothermal Engineer", "skill_name": "Sustainability"},
    {"job_title": "Advertising Marketer", "skill_name": "Advertising"},
    {"job_title": "Advertising Marketer", "skill_name": "Marketing Strategy"},
    {"job_title": "Advertising Marketer", "skill_name": "Creative Writing"},
    {"job_title": "Digital Marketer", "skill_name": "Digital Marketing"},
    {"job_title": "Digital Marketer", "skill_name": "SEO"},
    {"job_title": "Digital Marketer", "skill_name": "Content Creation"},
    {"job_title": "Content Marketer", "skill_name": "Content Creation"},
    {"job_title": "Content Marketer", "skill_name": "Marketing Strategy"},
    {"job_title": "Content Marketer", "skill_name": "SEO"},
    {"job_title": "Social Media Marketer", "skill_name": "Social Media"},
    {"job_title": "Social Media Marketer", "skill_name": "Content Creation"},
    {"job_title": "Social Media Marketer", "skill_name": "Marketing Strategy"},
    {"job_title": "Inbound Marketer", "skill_name": "Inbound Marketing"},
    {"job_title": "Inbound Marketer", "skill_name": "Content Creation"},
    {"job_title": "Inbound Marketer", "skill_name": "SEO"},
    {"job_title": "Outbound Marketer", "skill_name": "Outbound Marketing"},
    {"job_title": "Outbound Marketer", "skill_name": "Sales"},
    {
        "job_title": "Outbound Marketer",
        "skill_name": "Customer Relationship Management",
    },
]
